### PR TITLE
Fixed #4311 - creator.onUploadFile event is not fired for new image question

### LINKED ISSUE #4311: creator.onUploadFile event is not fired for new image question
To reproduce the issue, drop a new image question on the designer surface and load an image. creator.onUploadFile is not fired. It will be fired on loading the second, third... images.
Here is [the example ](https://codesandbox.io/s/surveyjs-angular-forked-mm3xzt?file=/src/app/components/creator.component.ts)to reproduce the issue.

### PR DESCRIPTION
**Pull request by tsv2013**

### CODE REVIEW

**Review by andrewtelnov — APPROVED** [review]

File: packages/survey-creator-core/src/components/question-image.ts [hunk 1]
```diff
@@ -12,16 +12,26 @@ export class QuestionImageAdornerViewModel extends QuestionAdornerViewModel {
...
+    surveyModel.onUploadFiles.add((s, o) => {
+      const fileToUpload = o.files[0];
+      if(!!fileToUpload) {
+        this.creator.uploadFiles(o.files, this.question, (status, link) => {
+          this.question.imageLink = link;
+        });
       }
-    };
+    });
+    // this.filePresentationModel.onPropertyValueChangedCallback = (name: string, oldValue: any, newValue: any, sender: Base, arrayChanges: any) => {
```
Comment (OlgaLarina) [inline packages/survey-creator-core/src/components/question-image.ts:30]: delete comment

Comment (tsv2013) [reply packages/survey-creator-core/src/components/question-image.ts]: Done

**Review by OlgaLarina — APPROVED** [review]
